#!/usr/bin/env python
#
# WARNING: generated data!  DO NOT EDIT MANUALLY ! ! !
#
# generated from  ../../../drivers/ui/menu/ui_menu_structure.c  at  2016-12-29T20:38:37+0000  by "./ui_menu_structure_c2py.sh"
#

MENU_DESCRIPTOR = [ dict(zip(["MENU_ID", "ME_KIND", "NR", "ID", "LABEL", "DESC"], e)) for e in [

       [ "MENU_TOP", "MEK_GROUP", "MENU_BASE", "STD","Standard Menu", "Operational parameters"  ],
       [ "MENU_TOP", "MEK_GROUP", "MENU_CONF", "CON","Configuration Menu", "Configuration settings typically not so often to be changed"  ],
       [ "MENU_TOP", "MEK_GROUP", "MENU_DISPLAY", "DIS","Display Menu", "Everything related to how the display presents data such as colors or speed of display"  ],
       [ "MENU_TOP", "MEK_GROUP", "MENU_CW","CW ","CW Mode Settings", "Everything related to CW Mode operation (except CW PA Bias)"  ],
       [ "MENU_TOP", "MEK_GROUP", "MENU_FILTER", "FIL","Filter Selection", "Select the filters for filter button by mode. Each mode can have up to 4 filters for quick selection via short press Filter button G4."  ],
       [ "MENU_TOP", "MEK_GROUP", "MENU_POW", "POW","PA Configuration", "Menu for power amplifier parameter and tune function adjustments"  ],
       [ "MENU_TOP", "MEK_GROUP", "MENU_SYSINFO","INF","System Info", "Lists various system info values"  ],
       [ "MENU_TOP", "MEK_GROUP", "MENU_DEBUG","INF","Debug/Exper. Settings", "As the name says, contains debug or expert settings usually not relevant for operating the mcHF"  ],
       [ "MENU_TOP", "MEK_STOP", 0, "   ", "NULL", ""  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_SSB_AUTO_MODE_SELECT","031","LSB/USB Auto Select", "If enabled, the appropriate sideband mode for SSB and FreeDV is chosen as default for bands by its frequency." ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_DIGI_DISABLE","030","Digital Modes", "Disable appearance of digital modes when pressing Mode button" ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_CW_DISABLE","030","CW Mode", "Disable appearance of CW mode when pressing Mode button" ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_AM_DISABLE","030","AM Mode", "Disable appearance of AM mode when pressing Mode button" ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_DEMOD_SAM","SAM","SyncAM Mode","Disable appearance of SyncAM modeswhen pressing Mode button"   ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_FM_MODE_ENABLE","040","FM Mode", "Disable appearance of FM mode when pressing Mode button" ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_FM_GEN_SUBAUDIBLE_TONE","041","FM Sub Tone Gen", "Enable generation of CTCSS tones during FM transmissions."  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_FM_DET_SUBAUDIBLE_TONE","042","FM Sub Tone Det", "Enable detection of CTCSS tones during FM receive. RX is muted unless tone is detected."  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_FM_TONE_BURST_MODE","043","FM Tone Burst", "Enabled sending of short tone at begin of each FM transmission. Used to open repeaters. Available frequencies are 1750 Hz and 2135 Hz."  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_FM_DEV_MODE","045","FM Deviation", "Select between normal and narrow deviation (5 and 2.5kHz) for FM RX/TX"  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_RF_GAIN_ADJ","051","RF Gain", "RF Receive Gain. This setting is also accessible via Encoder 2, RFG."  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_AGC_MODE","050","AGC Mode", "Automatic Gain Control Mode setting. You may select preconfigured settings (SLOW,MED,FAST), define settings yourself (CUSTOM) or use MANUAL (no AGC\, use RFG to control gain"  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_CUSTOM_AGC","052","Custom AGC (+=Slower)", "If AGC is set to CUSTOM\, this controls the speed setting of AGC"  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_CODEC_GAIN_MODE","053","RX Codec Gain", "Sets the Codec IQ signal gain. Higher values represent higher gain. If set to AUTO the mcHF controls the gain so that the dynamic range is used best."  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_RX_FREQ_CONV","055","RX/TX Freq Xlate", "Controls offset of the receiver IQ signal base frequency from the dial frequency. Use of +/-12Khz is recommended. Switching it to OFF is not recommended as it disables certain features."  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_MIC_LINE_MODE","060","Mic/Line Select", "Select used signal input for transmit (except in CW). Also changeable via long press on M3"  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_MIC_GAIN","061","Mic Input Gain", "Microphone gain. Also changeable via Encoder 3 if Microphone is selected as Input"  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_LINE_GAIN","062","Line Input Gain", "LineIn gain. Also changeable via Encoder 3 if LineIn Left (L>L) or LineIn Right (L>R) is selected as Input"  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_TX_COMPRESSION_LEVEL","065","TX Audio Compress", "Control the TX audio compressor. Higher values == more compression. Set to CUSTOM to set user defined compression parameters. See below. Also changeable via Encoder 1 (CMP)."  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_ALC_RELEASE","063","TX ALC Release Time", "If Audio Compressor Config is set to CUSTOM\, sets the value of the Audio Compressor Release time. Otherwise shows predefined value of selected compression level."  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_ALC_POSTFILT_GAIN","064","TX ALC Input Gain", "If Audio Compressor Config is set to CUSTOM\, sets the value of the ALC Input Gain. Otherwise shows predefined value of selected compression level."  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_NOISE_BLANKER_SETTING","054","RX NB Setting", "Set the Noise Blanker strength. Higher values mean more agressive blanking. Also changeable using Encoder 2 if Noise Blanker is active."  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_DSP_NR_STRENGTH", "010","DSP NR Strength", "Set the Noise Reduction Strength. Higher values mean more agressive noise reduction but also higher CPU load. Use with extreme care. Also changeable using Encoder 2 if DSP is active."  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_TCXO_MODE","090","TCXO Off/On/Stop", "The software TCXO can be turned ON (set frequency is adjusted so that generated frequency matches the wanted frequency); OFF (no correction or measurement done); or STOP (no correction but measurement)."  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_TCXO_C_F","091","TCXO Temp. (C/F)", "Show the measure TCXO temperature in Celsius or Fahrenheit."  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_BACKUP_CONFIG","197","Backup Config", "Backup your I2C Configuration to flash. If you don't have suitable I2C EEPROM installed this function is not available."  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_RESTORE_CONFIG","198","Restore Config", "Restore your I2C Configuration from flash. If you don't have suitable I2C EEPROM installed this function is not available."  ],
       [ "MENU_BASE", "MEK_ITEM", "MENU_RESTART_CODEC","198","Restart Codec", "Sometimes there is a problem with the I2S IQ signal stream from the Codec\, resulting in mirrored signal reception. Restarting the CODEC Stream will cure that problem. Try more than once\, if first call did not help."  ],
       [ "MENU_BASE", "MEK_STOP", 0, "   ", "NULL", ""  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "CONFIG_LCD_AUTO_OFF_MODE","090","LCD Auto Blank", ":soon:"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "CONFIG_FREQ_STEP_MARKER_LINE","091","Step Size Marker", "If enabled\, you'll see a line under the digit which is currently representing the selected step size"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "CONFIG_DISP_FILTER_BANDWIDTH","092","Filter BW Display", ":soon:"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_SPECTRUM_MODE","109","Spectrum Type", "Select if you want a scope-like or a waterfall-like (actually a fountain) display"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_SPECTRUM_MAGNIFY","105","Spectrum Magnify", "Select level of magnification of spectrum. Also changeable via touch screen."  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_SPECTRUM_SIZE","117","Spectrum Size", "Change height of spectrum display"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_SPECTRUM_FILTER_STRENGTH","101","Spectrum Filter", ":soon:"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_SPECTRUM_FREQSCALE_COLOUR","104","Spec FreqScale Colour", ":soon:"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_SPECTRUM_CENTER_LINE_COLOUR","108","Spec Line Colour", ":soon:"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "CONFIG_SPECTRUM_FFT_WINDOW_TYPE","340","Spectrum FFT Wind.", "Selects the use window algorithm for spectrum FFT"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_SCOPE_LIGHT_ENABLE","99","Scope Light", "The scope uses bars (NORMAL) or points (LIGHT) to represent data. LIGHT is a little less resource intensive."  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_SCOPE_SPEED","100","Scope 1/Speed", "Lower Values: Higher refresh rate"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_SCOPE_AGC_ADJUST","106","Scope AGC Adj.", ":soon:"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_SCOPE_TRACE_COLOUR","102","Scope Trace Colour", ":soon:"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_SCOPE_GRID_COLOUR","103","Scope Grid Colour", ":soon:"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_SCOPE_DB_DIVISION","107","Scope Div.", ":soon:"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_SCOPE_NOSIG_ADJUST","115","Scope NoSig Adj.", ":soon:"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_WFALL_SPEED","114","Wfall 1/Speed", "Lower Values: Higher refresh rate."  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_WFALL_COLOR_SCHEME","110","Wfall Colours", "Select colour scheme for waterfall display."  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_WFALL_STEP_SIZE","111","Wfall Step Size", "How many lines are moved in a single screen update"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_WFALL_OFFSET","112","Wfall Brightness", ":soon:"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_WFALL_CONTRAST","113","Wfall Contrast", ":soon:"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_WFALL_NOSIG_ADJUST","116","Wfall NoSig Adj.", ":soon:"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_METER_COLOUR_UP","122","Upper Meter Colour", "Set the colour of the scale of combined S/Power-Meter"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_METER_COLOUR_DOWN","123","Lower Meter Colour", "Set the colour of the scale of combined SWR/AUD/ALC-Meter"  ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_DBM_DISPLAY","120","dBm display", "Enable an additional numeric display of the RX signal strength" ],
       [ "MENU_DISPLAY", "MEK_ITEM", "MENU_S_METER","121","S-Meter", "Select the S-Meter measurement style. In old school mode, the RF Gain influence the S-Meter settings, higher RFG values increase S-Meter value." ],
       [ "MENU_DISPLAY", "MEK_STOP", 0, "   ", "NULL", ""  ],
       [ "MENU_CW", "MEK_ITEM", "MENU_KEYER_MODE","070","CW Keyer Mode", "Select how the mcHF interprets the connected keyer signals. Supported modes: Iambic A and B Keyer (IAM A/B)\, Straight Key (STR_K)\, and Ultimatic Keyer (ULTIM)"  ],
       [ "MENU_CW", "MEK_ITEM", "MENU_KEYER_SPEED","071","CW Keyer Speed", "Keyer Speed for the automatic keyer modes in WpM. Also changeable via Encoder 3 if in CW Mode."  ],
       [ "MENU_CW", "MEK_ITEM", "MENU_SIDETONE_GAIN","072","CW Sidetone Gain", "Audio volume for the monitor sidetone in CW TX. Also changeable via Encoder 1 if in CW Mode."  ],
       [ "MENU_CW", "MEK_ITEM", "MENU_SIDETONE_FREQUENCY","073","CW Side/Offset Freq", "Sidetone Frequency (also Offset frequency\, see CW Freq. Offset below)"  ],
       [ "MENU_CW", "MEK_ITEM", "MENU_PADDLE_REVERSE","074","CW Paddle Reverse", "Dit is Dah and Dah is Dit. Use if your keyer needs reverse meaning of the paddles."  ],
       [ "MENU_CW", "MEK_ITEM", "MENU_CW_TX_RX_DELAY","075","CW TX->RX Delay", "How long to stay in CW mode after stop sending a signal."  ],
       [ "MENU_CW", "MEK_ITEM", "MENU_CW_OFFSET_MODE","076","CW Freq. Offset", "TX: display is TX frequency if received frequency was zero-beated. DISP: display is RX frequency if received signal is matched to sidetone. SHIFT: LO shifts\, display is RX frequency if signal is matched to sidetone."  ],
       [ "MENU_CW", "MEK_ITEM", "MENU_CW_AUTO_MODE_SELECT","031","CW LSB/USB Select", "Set appropriate sideband mode for CW. If AUTO\, sideband is chosen for bands by its frequency. Long press on Mode button to get the other sideband mode" ],
       [ "MENU_CW", "MEK_STOP", 0, "   ", "NULL", ""  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_FREQ_MEM_LIMIT_RELAX","232","Save Out-Of-Band Freq.", "Select ON to save and restore frequencies which do not fit into the band during configuration saving (Power-Off or long press on Menu button)"  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_TX_OUT_ENABLE","207", "TX on Out-Of-Band Freq.", "Permit low power transmission even if the frequency is out of the official ham bands. DO NOT USE WITH CONNECTED ANTENNA! Use a dummy load!"  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_TX_DISABLE","203","Transmit Disable", "Disable all transmissions unconditionally. In CW you will be able to hear a sidetone but not transmission is made."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_AUDIO_MAIN_SCREEN_MENU_SWITCH","204","Menu SW on TX disable", "Control if the screen automatically adapts Encoder value focus when switching between RX and TX."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_MUTE_LINE_OUT_TX","205","TX Mute LineOut", "During transmission with frequency translation off line out will carry one of the two signal channels. Good for CW but not very useful otherwise. You may switch this signal off here."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_TXRX_SWITCH_AUDIO_MUTE","206","TX Initial Muting Time", "When switching from RX to TX the audio and HF output will be muted for roughly VALUE ms."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_MAX_VOLUME","210","Max Volume", ":soon:"  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_MAX_RX_GAIN","211","Max RX Gain (0=Max)", ":soon:"  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_BEEP_ENABLE","212","Key Beep", "If ON each keypress will generate a short beep"  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_BEEP_FREQ","213","Beep Frequency", "Set beep frequency in Hz."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_BEEP_VOLUME","214","Beep Volume", "Set beep volume."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_CAT_ENABLE","220","CAT Mode", "Enabled the FT 817 emulation via USB. See Wiki for more information."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_CAT_IN_SANDBOX","530","CAT Running In Sandbox", "If On\, frequency Changes made via CAT will not automatically switch bands and affect the manually selected frequencies."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_CAT_XLAT","400","CAT-DIQ-FREQ-XLAT", "Select which frequency is reported via CAT Interface to the connected PC in Digital IQ Mode. If OFF\, it reports the displayed frequency. If ON\, it reports the center frequency\, which is more useful with SDR programs."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_XVTR_OFFSET_MULT","280","XVTR Offs/Mult", "When connecting to a transverter\, set this to 1 and set the XVERTER Offset to the LO Frequency of it."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_XVTR_FREQUENCY_OFFSET","281","XVTR Offset", "When transverter mode is enabled\, this value is added to the mcHF frequency after being multiplied with the XVTR Offs/Mult. Use Step+ to set a good step width\, much less turns with the dial knob if it is set to 1Mhz"  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_STEP_SIZE_BUTTON_SWAP","201","Step Button Swap", "If ON\, Step- behaves like Step+ and vice versa."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_BAND_BUTTON_SWAP","202","Band+/- Button Swap", "If ON\, Band- behaves like Band+ and vice versa."  ],
       [ "MENU_CONF", "MEK_ITEM", "MENU_REVERSE_TOUCHSCREEN","122","Reverse Touchscreen", "Some touchscreens have the touch coordiantes reversed. In this case\, select ON"  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_VOLTMETER_CALIBRATION","208","Voltmeter Cal.", "Adjusts the displayed value of the voltmeter."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_FREQUENCY_CALIBRATE","230","Freq. Calibrate", "Adjust the frequency correction of the local oscillator. Select 1Hz step size and measure TX frequency and adjust until both match. Or receive a know reference signal and zero-beat it and then adjust. More information in the Wiki."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_RF_FWD_PWR_NULL","271","Pwr. Det. Null", ":soon:"  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_FWD_REV_SENSE_SWAP","276","FWD/REV ADC Swap.", ":soon:"  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_80M_RX_IQ_GAIN_BAL","240", "RX IQ Balance (80m)", "See Wiki Adjustments and Calibration."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_80M_RX_IQ_PHASE_BAL","241","RX IQ Phase   (80m)", "See Wiki Adjustments and Calibration."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_10M_RX_IQ_GAIN_BAL","242", "RX IQ Balance (10m)", "See Wiki Adjustments and Calibration."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_10M_RX_IQ_PHASE_BAL","243","RX IQ Phase   (10m)", "See Wiki Adjustments and Calibration."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_80M_TX_IQ_GAIN_BAL","250", "TX IQ Balance (80m)", "See Wiki Adjustments and Calibration."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_80M_TX_IQ_PHASE_BAL","251","TX IQ Phase   (80m)", "See Wiki Adjustments and Calibration."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_10M_TX_IQ_GAIN_BAL","252", "TX IQ Balance (10m)", "See Wiki Adjustments and Calibration."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_10M_TX_IQ_PHASE_BAL","253","TX IQ Phase   (10m)", "See Wiki Adjustments and Calibration."  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_DSP_NR_DECORRELATOR_BUFFER_LENGTH","310","DSP NR BufLen", ":soon:"  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_DSP_NR_FFT_NUMTAPS","311","DSP NR FFT NumTaps", ":soon:"  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_DSP_NR_POST_AGC_SELECT","312","DSP NR Post-AGC", ":soon:"  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_DSP_NOTCH_CONVERGE_RATE","313","DSP Notch ConvRate", ":soon:"  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_DSP_NOTCH_DECORRELATOR_BUFFER_LENGTH","314","DSP Notch BufLen", ":soon:"  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_DSP_NOTCH_FFT_NUMTAPS","315","DSP Notch FFTNumTap", ":soon:"  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_AGC_TIME_CONSTANT","320","NB AGC T/C (<=Slow)", ":soon:"  ],
       [ "MENU_CONF", "MEK_ITEM", "CONFIG_RESET_SER_EEPROM","341","Reset Config EEPROM", "Clear the EEPROM so that at next start all stored configuration data is reset to the values stored in Flash (see Backup/Restore)."  ],
       [ "MENU_CONF", "MEK_STOP", 0, "   ", "NULL", ""  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_TUNE_POWER_LEVEL","P00","Tune Power Level", "Select the power level for TUNE operation. May be set to follow the selected power level or have a fixed power level."  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_TUNE_TONE_MODE","P99","Tune Tone (SSB)", "Select if single tone or two tone is generated during TUNE operation. Not persistent."  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_CW_PA_BIAS","260","CW PA Bias (If >0 )", "If set to a value above 0, this BIAS is used during CW transmission; otherwise normal BIAS is used during CW"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_REDUCE_POWER_ON_LOW_BANDS","P0A","Reduce Power on Low Bands", "If set (recommended!)  frequencies below 8Mhz require higher power adjust values. This permits better control of generated power on these frequencies."  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_PA_BIAS","261","PA Bias", "Defines the BIAS value of the PA. See Adjustment and Calibration for more information."  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_2200M_5W_ADJUST","P01","2200m 5W PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_630M_5W_ADJUST","P02","630m  5W PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_160M_5W_ADJUST","P03","160m  5W PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_80M_5W_ADJUST","P04","80m   5W PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_60M_5W_ADJUST","P05","60m   5W PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_40M_5W_ADJUST","P06","40m   5W PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_30M_5W_ADJUST","P07","30m   5W PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_20M_5W_ADJUST","P08","20m   5W PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_17M_5W_ADJUST","P09","17m   5W PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_15M_5W_ADJUST","P10","15m   5W PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_12M_5W_ADJUST","P11","12m   5W PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_10M_5W_ADJUST","P12","10m   5W PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_6M_5W_ADJUST","P13","6m    5W PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_4M_5W_ADJUST","P14","4m    5W PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_2M_5W_ADJUST","P15","2m    5W PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_70CM_5W_ADJUST","P16","70cm  5W PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_23CM_5W_ADJUST","P17","23cm  5W PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_2200M_FULL_POWER_ADJUST","O01","2200m Full PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_630M_FULL_POWER_ADJUST","O02","630m  Full PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_160M_FULL_POWER_ADJUST","O03","160m  Full PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_80M_FULL_POWER_ADJUST","O04","80m   Full PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_60M_FULL_POWER_ADJUST","O05","60m   Full PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_40M_FULL_POWER_ADJUST","O06","40m   Full PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_30M_FULL_POWER_ADJUST","O07","30m   Full PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_20M_FULL_POWER_ADJUST","O08","20m   Full PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_17M_FULL_POWER_ADJUST","O09","17m   Full PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_15M_FULL_POWER_ADJUST","O10","15m   Full PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_12M_FULL_POWER_ADJUST","O11","12m   Full PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_10M_FULL_POWER_ADJUST","O12","10m   Full PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_6M_FULL_POWER_ADJUST","O13","6m    Full PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_4M_FULL_POWER_ADJUST","O14","4m    Full PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_2M_FULL_POWER_ADJUST","O15","2m    Full PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_70CM_FULL_POWER_ADJUST","O16","70cm  Full PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_23CM_FULL_POWER_ADJUST","O17","23cm  Full PWR Adjust", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_FWD_REV_COUPLING_2200M_ADJ","C01","2200m Coupling Adj.", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_FWD_REV_COUPLING_630M_ADJ","C02","630m Coupling Adj.", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_FWD_REV_COUPLING_160M_ADJ","C03","160m Coupling Adj.", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_FWD_REV_COUPLING_80M_ADJ","C04","80m  Coupling Adj.", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_FWD_REV_COUPLING_40M_ADJ","C05","40m  Coupling Adj.", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_FWD_REV_COUPLING_20M_ADJ","C06","20m  Coupling Adj.", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_FWD_REV_COUPLING_15M_ADJ","C07","15m  Coupling Adj.", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_FWD_REV_COUPLING_6M_ADJ","C08","6m   Coupling Adj.", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_FWD_REV_COUPLING_2M_ADJ","C09","2m   Coupling Adj.", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_FWD_REV_COUPLING_70CM_ADJ","C10","70cm Coupling Adj.", ":soon:"  ],
       [ "MENU_POW", "MEK_ITEM", "CONFIG_FWD_REV_COUPLING_23CM_ADJ","C11","23cm Coupling Adj.", ":soon:"  ],
       [ "MENU_POW", "MEK_STOP", 0, "   ", "NULL", ""  ],
       [ "MENU_FILTER", "MEK_ITEM", "MENU_FP_SSB_01","600", "SSB Filter 1", ":soon:"  ],
       [ "MENU_FILTER", "MEK_ITEM", "MENU_FP_SSB_02","600", "SSB Filter 2", ":soon:"  ],
       [ "MENU_FILTER", "MEK_ITEM", "MENU_FP_SSB_03","600", "SSB Filter 3", ":soon:"  ],
       [ "MENU_FILTER", "MEK_ITEM", "MENU_FP_SSB_04","600", "SSB Filter 4", ":soon:"  ],
       [ "MENU_FILTER", "MEK_ITEM", "MENU_FP_CW_01","600", "CW Filter 1", ":soon:"  ],
       [ "MENU_FILTER", "MEK_ITEM", "MENU_FP_CW_02","600", "CW Filter 2", ":soon:"  ],
       [ "MENU_FILTER", "MEK_ITEM", "MENU_FP_CW_03","600", "CW Filter 3", ":soon:"  ],
       [ "MENU_FILTER", "MEK_ITEM", "MENU_FP_CW_04","600", "CW Filter 4", ":soon:"  ],
       [ "MENU_FILTER", "MEK_ITEM", "MENU_FP_AM_01","600", "AM Filter 1", ":soon:"  ],
       [ "MENU_FILTER", "MEK_ITEM", "MENU_FP_AM_02","600", "AM Filter 2", ":soon:"  ],
       [ "MENU_FILTER", "MEK_ITEM", "MENU_FP_AM_03","600", "AM Filter 3", ":soon:"  ],
       [ "MENU_FILTER", "MEK_ITEM", "MENU_FP_AM_04","600", "AM Filter 4", ":soon:"  ],
       [ "MENU_FILTER", "MEK_ITEM", "MENU_FP_SAM_01","600", "SAM Filter 1", ":soon:"  ],
       [ "MENU_FILTER", "MEK_ITEM", "MENU_FP_SAM_02","600", "SAM Filter 2", ":soon:"  ],
       [ "MENU_FILTER", "MEK_ITEM", "MENU_FP_SAM_03","600", "SAM Filter 3", ":soon:"  ],
       [ "MENU_FILTER", "MEK_ITEM", "MENU_FP_SAM_04","600", "SAM Filter 4", ":soon:"  ],
       [ "MENU_FILTER", "MEK_ITEM", "CONFIG_AM_TX_FILTER_DISABLE","330","AM  TX Audio Filter", ":soon:"  ],
       [ "MENU_FILTER", "MEK_ITEM", "CONFIG_SSB_TX_FILTER","332","SSB TX Audio Filter2", ":soon:"  ],
       [ "MENU_FILTER", "MEK_STOP", 0, "   ", "NULL", ""  ],
       [ "MENU_SYSINFO", "MEK_INFO", "INFO_DISPLAY","I01","Display", ":soon:"  ],
       [ "MENU_SYSINFO", "MEK_INFO", "INFO_DISPLAY_CTRL","I02","Disp. Controller", ":soon:"  ],
       [ "MENU_SYSINFO", "MEK_INFO", "INFO_SI570","I02","SI570", ":soon:"  ],
       [ "MENU_SYSINFO", "MEK_INFO", "INFO_EEPROM","I03","EEPROM", ":soon:"  ],
       [ "MENU_SYSINFO", "MEK_INFO", "INFO_TP","I04","Touchscreen", ":soon:"  ],
       [ "MENU_SYSINFO", "MEK_INFO", "INFO_CPU","I07","CPU", ":soon:"  ],
       [ "MENU_SYSINFO", "MEK_INFO", "INFO_FLASH","I07","Flash Size (kB)", ":soon:"  ],
       [ "MENU_SYSINFO", "MEK_INFO", "INFO_RAM","I08","RAM Size (kB)", ":soon:"  ],
       [ "MENU_SYSINFO", "MEK_INFO", "INFO_FW_VERSION","I08","Firmware", ":soon:"  ],
       [ "MENU_SYSINFO", "MEK_INFO", "INFO_BUILD","I08","Build", ":soon:"  ],
       [ "MENU_SYSINFO", "MEK_INFO", "INFO_BL_VERSION","I08","Bootloader", ":soon:"  ],
       [ "MENU_SYSINFO", "MEK_INFO", "INFO_RFMOD","I05","RF Bands Mod", ":soon:"  ],
       [ "MENU_SYSINFO", "MEK_INFO", "INFO_VHFUHFMOD","I06","V/UHF Mod", ":soon:"  ],
       [ "MENU_SYSINFO", "MEK_STOP", 0, "   ", "NULL", ""  ],
       [ "MENU_DEBUG", "MEK_ITEM", "MENU_DEBUG_TX_AUDIO","028","TX Audio via USB", ":soon:"  ],
       [ "MENU_DEBUG", "MEK_STOP", 0, "   ", "NULL", ""  ],

   ]
]

#EOFILE
