rm -f Inc/usbd_audio_if.h
rm -f Inc/usbd_desc.h
rm -f Src/usbd_audio_if.c
rm -f Src/usbd_desc.c
rm -f Src/usb_device.c
rm -rf Middlewares/ST/STM32_USB_Host_Library/Class/AUDIO
rm -rf Middlewares/ST/STM32_USB_Host_Library/Class/CDC
rm -rf Middlewares/ST/STM32_USB_Host_Library/Class/MTP
rm -rf Middlewares/ST/STM32_USB_Host_Library/Class/HID
rm -rf Drivers/CMSIS/Lib
