drivers/ui/radio_management.o: drivers/ui/radio_management.c \
 drivers/ui/radio_management.h hardware/uhsdr_types.h \
 basesw/ovi40-h7/Drivers/CMSIS/DSP/Include/arm_math.h \
 basesw/ovi40-h7/Drivers/CMSIS/Include/core_cm7.h \
 basesw/ovi40-h7/Drivers/CMSIS/Include/cmsis_compiler.h \
 basesw/ovi40-h7/Drivers/CMSIS/Include/cmsis_gcc.h hardware/uhsdr_board.h \
 hardware/uhsdr_board_config.h \
 hardware/board_configs/UHSDR_UI_ovi40_config.h \
 basesw/ovi40-h7/Drivers/CMSIS/Device/ST/STM32H7xx/Include/stm32h7xx.h \
 basesw/ovi40-h7/Drivers/CMSIS/Device/ST/STM32H7xx/Include/stm32h743xx.h \
 basesw/ovi40-h7/Drivers/CMSIS/Device/ST/STM32H7xx/Include/system_stm32h7xx.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal.h \
 basesw/ovi40-h7/Inc/stm32h7xx_hal_conf.h basesw/ovi40-h7/Inc/main.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_rcc.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_def.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_rcc_ex.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_gpio.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_gpio_ex.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_dma.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_dma_ex.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_cortex.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_adc.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_adc_ex.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_dac.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_dac_ex.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_flash.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_flash_ex.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_hsem.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_sram.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_ll_fmc.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_mdma.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_i2c.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_i2c_ex.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_mdma.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_pwr.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_pwr_ex.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_rtc.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_rtc_ex.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_sai.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_sai_ex.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_spi.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_spi_ex.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_tim.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_tim_ex.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_pcd.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_ll_usb.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_pcd_ex.h \
 basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_hcd.h \
 hardware/board_configs/UHSDR_RF_ovi40_config.h \
 hardware/board_configs/UHSDR_RF_mchf_config.h hardware/uhsdr_types.h \
 hardware/uhsdr_mcu.h drivers/audio/audio_filter.h \
 drivers/ui/oscillator/osc_interface.h drivers/ui/lcd/ui_lcd_layouts.h \
 drivers/ui/lcd/ui_lcd_hy28.h drivers/ui/ui_vkeybrd.h \
 drivers/audio/audio_driver.h hardware/uhsdr_board_config.h \
 drivers/audio/softdds/softdds.h drivers/audio/softdds/dds_table.h \
 drivers/audio/audio_filter.h misc/profiling.h basesw/ovi40-h7/Inc/adc.h \
 drivers/ui/oscillator/soft_tcxo.h hardware/uhsdr_hw_i2c.h \
 basesw/ovi40-h7/Inc/i2c.h drivers/audio/freedv_uhsdr.h \
 drivers/freedv/comp.h drivers/audio/rb.h drivers/audio/codec/codec.h \
 drivers/ui/ui_configuration.h drivers/audio/audio_management.h \
 drivers/cat/cat_driver.h drivers/ui/lcd/ui_spectrum.h \
 basesw/ovi40-h7/Drivers/CMSIS/DSP/Include/arm_const_structs.h \
 basesw/ovi40-h7/Drivers/CMSIS/DSP/Include/arm_math.h \
 basesw/ovi40-h7/Drivers/CMSIS/DSP/Include/arm_common_tables.h \
 drivers/ui/lcd/ui_lcd_layouts.h drivers/ui/ui_configuration.h \
 drivers/ui/menu/ui_menu.h misc/config_storage.h \
 drivers/audio/cw/cw_gen.h drivers/audio/cw/cw_decoder.h \
 drivers/audio/psk.h drivers/audio/rtty.h \
 drivers/audio/cw/uhsdr_digi_buffer.h drivers/audio/audio_nr.h \
 drivers/audio/freedv_uhsdr.h

drivers/ui/radio_management.h:

hardware/uhsdr_types.h:

basesw/ovi40-h7/Drivers/CMSIS/DSP/Include/arm_math.h:

basesw/ovi40-h7/Drivers/CMSIS/Include/core_cm7.h:

basesw/ovi40-h7/Drivers/CMSIS/Include/cmsis_compiler.h:

basesw/ovi40-h7/Drivers/CMSIS/Include/cmsis_gcc.h:

hardware/uhsdr_board.h:

hardware/uhsdr_board_config.h:

hardware/board_configs/UHSDR_UI_ovi40_config.h:

basesw/ovi40-h7/Drivers/CMSIS/Device/ST/STM32H7xx/Include/stm32h7xx.h:

basesw/ovi40-h7/Drivers/CMSIS/Device/ST/STM32H7xx/Include/stm32h743xx.h:

basesw/ovi40-h7/Drivers/CMSIS/Device/ST/STM32H7xx/Include/system_stm32h7xx.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal.h:

basesw/ovi40-h7/Inc/stm32h7xx_hal_conf.h:

basesw/ovi40-h7/Inc/main.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_rcc.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_def.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_rcc_ex.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_gpio.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_gpio_ex.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_dma.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_dma_ex.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_cortex.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_adc.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_adc_ex.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_dac.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_dac_ex.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_flash.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_flash_ex.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_hsem.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_sram.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_ll_fmc.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_mdma.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_i2c.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_i2c_ex.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_mdma.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_pwr.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_pwr_ex.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_rtc.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_rtc_ex.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_sai.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_sai_ex.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_spi.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_spi_ex.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_tim.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_tim_ex.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_pcd.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_ll_usb.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_pcd_ex.h:

basesw/ovi40-h7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_hcd.h:

hardware/board_configs/UHSDR_RF_ovi40_config.h:

hardware/board_configs/UHSDR_RF_mchf_config.h:

hardware/uhsdr_types.h:

hardware/uhsdr_mcu.h:

drivers/audio/audio_filter.h:

drivers/ui/oscillator/osc_interface.h:

drivers/ui/lcd/ui_lcd_layouts.h:

drivers/ui/lcd/ui_lcd_hy28.h:

drivers/ui/ui_vkeybrd.h:

drivers/audio/audio_driver.h:

hardware/uhsdr_board_config.h:

drivers/audio/softdds/softdds.h:

drivers/audio/softdds/dds_table.h:

drivers/audio/audio_filter.h:

misc/profiling.h:

basesw/ovi40-h7/Inc/adc.h:

drivers/ui/oscillator/soft_tcxo.h:

hardware/uhsdr_hw_i2c.h:

basesw/ovi40-h7/Inc/i2c.h:

drivers/audio/freedv_uhsdr.h:

drivers/freedv/comp.h:

drivers/audio/rb.h:

drivers/audio/codec/codec.h:

drivers/ui/ui_configuration.h:

drivers/audio/audio_management.h:

drivers/cat/cat_driver.h:

drivers/ui/lcd/ui_spectrum.h:

basesw/ovi40-h7/Drivers/CMSIS/DSP/Include/arm_const_structs.h:

basesw/ovi40-h7/Drivers/CMSIS/DSP/Include/arm_math.h:

basesw/ovi40-h7/Drivers/CMSIS/DSP/Include/arm_common_tables.h:

drivers/ui/lcd/ui_lcd_layouts.h:

drivers/ui/ui_configuration.h:

drivers/ui/menu/ui_menu.h:

misc/config_storage.h:

drivers/audio/cw/cw_gen.h:

drivers/audio/cw/cw_decoder.h:

drivers/audio/psk.h:

drivers/audio/rtty.h:

drivers/audio/cw/uhsdr_digi_buffer.h:

drivers/audio/audio_nr.h:

drivers/audio/freedv_uhsdr.h:
