BLSRC := \
src/bootloader/bootloader_main.c \
src/bootloader/command.c \
src/bootloader/uhsdr_boot_hw.c \
src/bootloader/flash_if.c \
drivers/ui/lcd/ui_lcd_hy28.c \
drivers/ui/lcd/ui_lcd_hy28_fonts.c \
basesw/uhsdr/Src/adc.c \
basesw/uhsdr/Src/dac.c \
basesw/uhsdr/Src/dma.c \
basesw/uhsdr/Src/fatfs.c \
basesw/uhsdr/Src/fsmc.c \
basesw/uhsdr/Src/gpio.c \
basesw/uhsdr/Src/i2c.c \
basesw/uhsdr/Src/i2s.c \
basesw/uhsdr/Src/main.c \
basesw/uhsdr/Src/rtc.c \
basesw/uhsdr/Src/spi.c \
basesw/uhsdr/Src/stm32f4xx_hal_msp.c \
basesw/uhsdr/Src/stm32f4xx_it.c \
basesw/uhsdr/Src/tim.c \
basesw/uhsdr/Src/usb_host.c \
basesw/uhsdr/Src/usbd_conf.c \
basesw/uhsdr/Src/usbh_conf.c \
basesw/uhsdr/Src/user_diskio.c \
basesw/uhsdr/Middlewares/Third_Party/FatFs/src/option/syscall.c \
basesw/uhsdr/Middlewares/Third_Party/FatFs/src/option/unicode.c \
basesw/uhsdr/Middlewares/Third_Party/FatFs/src/drivers/usbh_diskio.c \
basesw/uhsdr/Middlewares/Third_Party/FatFs/src/diskio.c \
basesw/uhsdr/Middlewares/Third_Party/FatFs/src/ff.c \
basesw/uhsdr/Middlewares/Third_Party/FatFs/src/ff_gen_drv.c \
basesw/uhsdr/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_core.c \
basesw/uhsdr/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_ctlreq.c \
basesw/uhsdr/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_ioreq.c \
basesw/uhsdr/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_pipes.c \
basesw/uhsdr/Middlewares/ST/STM32_USB_Host_Library/Class/MTP/Src/usbh_mtp.c \
basesw/uhsdr/Middlewares/ST/STM32_USB_Host_Library/Class/MTP/Src/usbh_mtp_ptp.c \
basesw/uhsdr/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc.c \
basesw/uhsdr/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc_bot.c \
basesw/uhsdr/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc_scsi.c \
basesw/uhsdr/Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src/usbh_hid.c \
basesw/uhsdr/Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src/usbh_hid_keybd.c \
basesw/uhsdr/Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src/usbh_hid_mouse.c \
basesw/uhsdr/Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src/usbh_hid_parser.c \
basesw/uhsdr/Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Src/usbh_cdc.c \
basesw/uhsdr/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c \
basesw/uhsdr/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c \
basesw/uhsdr/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cec.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp_ex.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi_ex.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dfsdm.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma2d.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dsi.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpi2c.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpi2c_ex.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash_ex.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s_ex.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_lptim.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc_ex.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_qspi.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc_ex.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai_ex.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sdram.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spdifrx.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmc.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c \
basesw/uhsdr/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c \
basesw/uhsdr/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/startup_stm32f407xx.S \
basesw/uhsdr/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/system_stm32f4xx.c \
\
