BLSRC := \
src/bootloader/command.c \
src/bootloader/flash_if.c \
src/bootloader/mchf_boot_hw.c \
src/bootloader/bootloader_main.c \
drivers/ui/lcd/ui_lcd_hy28.c \
drivers/ui/lcd/ui_lcd_hy28_fonts.c \
basesw/abCD15/Src/adc.c \
basesw/abCD15/Src/dac.c \
basesw/abCD15/Src/dma.c \
basesw/abCD15/Src/fatfs.c \
basesw/abCD15/Src/fmc.c \
basesw/abCD15/Src/gpio.c \
basesw/abCD15/Src/i2c.c \
basesw/abCD15/Src/main.c \
basesw/abCD15/Src/rtc.c \
basesw/abCD15/Src/sai.c \
basesw/abCD15/Src/spi.c \
basesw/abCD15/Src/stm32f7xx_hal_msp.c \
basesw/abCD15/Src/stm32f7xx_it.c \
basesw/abCD15/Src/tim.c \
basesw/abCD15/Src/usb_host.c \
basesw/abCD15/Src/usb_otg_fs.c \
basesw/abCD15/Src/usbd_conf.c \
basesw/abCD15/Src/usbh_conf.c \
basesw/abCD15/Middlewares/Third_Party/FatFs/src/option/syscall.c \
basesw/abCD15/Middlewares/Third_Party/FatFs/src/option/unicode.c \
basesw/abCD15/Middlewares/Third_Party/FatFs/src/drivers/usbh_diskio.c \
basesw/abCD15/Middlewares/Third_Party/FatFs/src/diskio.c \
basesw/abCD15/Middlewares/Third_Party/FatFs/src/ff.c \
basesw/abCD15/Middlewares/Third_Party/FatFs/src/ff_gen_drv.c \
basesw/abCD15/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_core.c \
basesw/abCD15/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_ctlreq.c \
basesw/abCD15/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_ioreq.c \
basesw/abCD15/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_pipes.c \
basesw/abCD15/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc.c \
basesw/abCD15/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc_bot.c \
basesw/abCD15/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc_scsi.c \
basesw/abCD15/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c \
basesw/abCD15/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c \
basesw/abCD15/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_can.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cec.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc_ex.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp_ex.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac_ex.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi_ex.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dfsdm.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dsi.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash_ex.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hcd.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2s.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_irda.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_iwdg.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_jpeg.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_lptim.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mdios.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mmc.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nand.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nor.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_qspi.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rng.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc_ex.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai_ex.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sd.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sdram.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard_ex.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smbus.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spdifrx.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sram.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_usart.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_wwdg.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_adc.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_crc.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dac.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma2d.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_exti.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_fmc.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_gpio.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_i2c.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_lptim.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_pwr.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rcc.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rng.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rtc.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_sdmmc.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_spi.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_tim.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usart.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.c \
basesw/abCD15/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_utils.c \
basesw/abCD15/Drivers/CMSIS/Device/ST/STM32F7xx/Source/Templates/gcc/startup_stm32f767xx.S \
basesw/abCD15/Drivers/CMSIS/Device/ST/STM32F7xx/Source/Templates/system_stm32f7xx.c \

