SUBDIRS := \
. \
basesw/mcHF/Inc \
basesw/mcHF/Drivers/CMSIS/Device/ST/STM32F4xx/Include \
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc \
basesw/mcHF/Drivers/CMSIS/Include \
basesw/mcHF/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Inc \
basesw/mcHF/Middlewares/ST/STM32_USB_Device_Library/Core/Inc \
basesw/mcHF/Middlewares/ST/STM32_USB_Host_Library/Class/AUDIO/Inc \
basesw/mcHF/Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc \
basesw/mcHF/Middlewares/ST/STM32_USB_Host_Library/Class/HID/Inc \
basesw/mcHF/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc \
basesw/mcHF/Middlewares/ST/STM32_USB_Host_Library/Class/MTP/Inc \
basesw/mcHF/Middlewares/ST/STM32_USB_Host_Library/Core/Inc \
hardware \
drivers/freedv \
drivers/audio \
drivers/ui/oscillator \
drivers/ui/ \
misc/v_eprom \
drivers/ui/lcd \
drivers/ui/encoder \
drivers/audio/codec \
drivers/audio/softdds \
misc \
drivers/audio/cw \
drivers/ui/menu \
 \
drivers/cat \
drivers/audio/filters \
src \
src/bootloader \
drivers/diag \
basesw/mcHF/Middlewares/Third_Party/FatFs/src \
basesw/mcHF/Middlewares/Third_Party/FatFs/src/drivers \
basesw/mcHF/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc \
basesw/mcHF/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc \
drivers/usb/device/class/composite \

